version: '3.8'
services:
    postgres:
        image: postgres:14-alpine
        container_name: database_server
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - "POSTGRES_USER=Votre nom d'utilisateur"
            - "POSTGRES_PASSWORD=Votre mot de passe"
            - "POSTGRES_DB=Votre nom de base de donnée"
        restart: unless-stopped
volumes:
  postgres-data:
    external: true